
services:
  postgres:
    image: postgres:15-alpine
    container_name: ers-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - ers-network

  redis:
    image: redis:7-alpine
    container_name: ers-redis
    ports:
      - "6380:6379"
    networks:
      - ers-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: ers-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ers-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: ers-auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DATABASE_URL=jdbc:postgresql://postgres:5432/auth_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=0000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=vNhpXqI4ZNInZ94Ka8Husuq0hdV5G0FSxy7GkMP5F84=
    depends_on:
      - postgres
      - redis
    networks:
      - ers-network

  incident-service:
    build:
      context: ./incident-service
      dockerfile: Dockerfile
    container_name: ers-incident-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DATABASE_URL=jdbc:postgresql://postgres:5432/incident_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=0000
      - RABBITMQ_HOST=rabbitmq
      - SECRET_KEY=vNhpXqI4ZNInZ94Ka8Husuq0hdV5G0FSxy7GkMP5F84=
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - ers-network

  tracking-service:
    build:
      context: ./tracking-service
      dockerfile: Dockerfile
    container_name: ers-tracking-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DATABASE_URL=jdbc:postgresql://postgres:5432/tracking_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=0000
      - RABBITMQ_HOST=rabbitmq
      - SECRET_KEY=vNhpXqI4ZNInZ94Ka8Husuq0hdV5G0FSxy7GkMP5F84=
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - ers-network

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: ers-analytics-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DATABASE_URL_INCIDENT=jdbc:postgresql://postgres:5432/incident_db
      - DATABASE_URL_TRACKING=jdbc:postgresql://postgres:5432/tracking_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=0000
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=vNhpXqI4ZNInZ94Ka8Husuq0hdV5G0FSxy7GkMP5F84=
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - ers-network

networks:
  ers-network:
    driver: bridge

volumes:
  postgres-data: {}
  
