services:
  redis:
    image: redis:7-alpine
    container_name: ers-redis
    ports:
      - "6380:6379"
    networks:
      - ers-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: ers-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ers-network

  auth-service:
    build:
      context: ./auth-service
    container_name: ers-auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://ep-tiny-haze-alhosxxv-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      DATABASE_USERNAME: neondb_owner
      DATABASE_PASSWORD: npg_esNV0tJ7oMPp
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: vNhpXqI4ZNInZ94Ka8Husuq0hdV5G0FSxy7GkMP5F84=
    depends_on:
      - redis
    networks:
      - ers-network

  incident-service:
    build:
      context: ./incident-service
    container_name: ers-incident-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://ep-aged-snow-agkhfmzm-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      DATABASE_USERNAME: neondb_owner
      DATABASE_PASSWORD: npg_92lgqKQHAeZd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      RABBITMQ_HOST: rabbitmq
      SECRET_KEY: vNhpXqI4ZNInZ94Ka8Husuq0hdV5G0FSxy7GkMP5F84=
      AUTH_SERVICE_URL: http://auth-service:8081
    depends_on:
      - rabbitmq
      - auth-service
    networks:
      - ers-network

  tracking-service:
    build:
      context: ./tracking-service
    container_name: ers-tracking-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://ep-empty-wildflower-ag2ksppo-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      DATABASE_USERNAME: neondb_owner
      DATABASE_PASSWORD: npg_3oCv8bFMUNpP
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      RABBITMQ_HOST: rabbitmq
      SECRET_KEY: vNhpXqI4ZNInZ94Ka8Husuq0hdV5G0FSxy7GkMP5F84=
      AUTH_SERVICE_URL: http://auth-service:8081
    depends_on:
      - rabbitmq
      - auth-service
    networks:
      - ers-network

  analytics-service:
    build:
      context: ./analytics-service
    container_name: ers-analytics-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL_INCIDENT: jdbc:postgresql://ep-aged-snow-agkhfmzm-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      DATABASE_URL_TRACKING: jdbc:postgresql://ep-empty-wildflower-ag2ksppo-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      DATABASE_USERNAME: neondb_owner
      INCIDENT_DB_PASSWORD: npg_92lgqKQHAeZd
      TRACKING_DB_PASSWORD: npg_3oCv8bFMUNpP
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: vNhpXqI4ZNInZ94Ka8Husuq0hdV5G0FSxy7GkMP5F84=
      AUTH_SERVICE_URL: http://auth-service:8081
    depends_on:
      - rabbitmq
      - redis
      - auth-service
    networks:
      - ers-network

networks:
  ers-network:
    driver: bridge
